### ISSUE TITLE
Fallback to backup resume list when emerge is running

### ISSUE THREAD

**Issue by vincentdephily** [vincentdephily/emlop#50]
`emerge --keep-going` might end up using the "backup" resume list from `/var/cache/edb/mtimedb` when restarting, so emlop should read that if the main resume list is empty.

Or maybe that's still a fallible heuristic, and we need something smarter ?

**Comment by kakra** [comment]
During the profile update, I ran `emerge -e @world` as instructed in the end of the news item.

While 2800 packages were emerging, some of them failed. So I opened a second terminal, fixed the issue (usually, just the git cache of a `-9999` ebuild was broken), and emerged the package. Sometimes packages would build just fine on the second try (`ffmpeg` belongs to this class of packages, maybe due to circular deps, or maybe because parallel make is broken in those packages).

If I did this, `emlop p` would show only two packages building: The one I just built, and it would stay there, and the one the main emerge is currently building. After the main emerge picked up the next packages to build, `emlop p` showed the complete set of packages in queue again.

Maybe this is the same issue?

**Comment by vincentdephily** [comment]
Not showing the complete set is AFAICT the same issue (with an easy fix, just need to get around to it). Note that emlop will only ever show one full merge set, the one that  `emerge --resume` would pick.

Regarding the "package you just built" being shown by emlop, are you sure that the emerge of that package had completely finished ? If so, it's a different bug. Emlop 0.7 uses a better heuristic to find the current builds, but it's probably not perfect. If you encounter it again, please open an issue with as much info as you can, using `emlop -vvvv p` and maybe `pgrep emerge|xargs -n1 pstree -ap`.

**Comment by vincentdephily** [comment]
Going to close this with the fix I originally intended.

Not 100% what the other issue is, but I doubt it's fixable as long as emlop relies on the mtimedb file that portage writes with various concurrency gotchas.
